#!/bin/bash

current_branch_name=$(git rev-parse --abbrev-ref HEAD)
if [ $current_branch_name = master ]
then

pylint --recursive=y . &&

make test

else
  echo we are not in master, do not run tests and linting
fi
